In [1]:
import pysradb
from pysradb.sraweb import SRAweb
db = SRAweb()

/home/wt/pysradb/pysradb/download.py:14: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm

In [2]:
import pandas as pd

In [3]:
all_srr = pd.read_csv("/home/wt/GEO_data/SRA/curr_files",header=None,names=["srr"])

In [4]:
all_srr

            srr
0   SRR10980127
1   SRR10980128
2   SRR10980129
3   SRR10980130
4   SRR10980131
5   SRR10980132
6   SRR11059047
7   SRR19242986
8   SRR24997945
9   SRR32238155
10  SRR33556578
11  SRR33556580
12    SRR390728
13   SRR5800675
14   SRR5800676
15   SRR5800677
16   SRR6181915

In [5]:
from tqdm import tqdm
import sys 
import time

In [6]:
for i in tqdm(range(len(all_srr))):
    try:
        df = db.sra_metadata(all_srr.srr[i], detailed=True,output_read_lengths=True)
        df.to_csv("metadata/"+str(all_srr.srr[i])+".txt",sep="\t", index=False)
    except:
        time.sleep(20)
        try:
            df = db.sra_metadata(all_srr.srr[i], detailed=True,output_read_lengths=True)
            df.to_csv("metadata/"+str(all_srr.srr[i])+".txt",sep="\t", index=False)
        except:
            time.sleep(20)

 41%|████      | 7/17 [01:12<01:42, 10.21s/it]

No results found for ['SRP046387'] | Obtained result: {}

 47%|████▋     | 8/17 [01:44<02:35, 17.28s/it]

No results found for ['SRX15303695'] | Obtained result: {}
No results found for ['SRP445393'] | Obtained result: {}

 53%|█████▎    | 9/17 [01:54<01:59, 14.96s/it]

No results found for ['SRP561730'] | Obtained result: {}

 59%|█████▉    | 10/17 [02:03<01:31, 13.13s/it]

No results found for ['SRP585103'] | Obtained result: {}

 65%|██████▍   | 11/17 [02:13<01:12, 12.05s/it]

No results found for ['SRP585103'] | Obtained result: {}

 71%|███████   | 12/17 [02:22<00:56, 11.31s/it]

No results found for ['SRP020237'] | Obtained result: {}

 76%|███████▋  | 13/17 [02:31<00:42, 10.53s/it]

No results found for ['SRX079566'] | Obtained result: {}

100%|██████████| 17/17 [03:13<00:00, 11.37s/it]

In [7]:
df

,run_accession,study_accession,study_title,experiment_accession,experiment_title,experiment_desc,organism_taxid,organism_name,library_name,library_strategy,...,cell type,treatment,ena_fastq_http,ena_fastq_http_1,ena_fastq_http_2,ena_fastq_ftp,ena_fastq_ftp_1,ena_fastq_ftp_2,study_geo_accession,experiment_geo_accession
0,SRR6181915,SRP120158,Targeting multiple effector pathways in pancre...,SRX3292265,GSM2817751: MIAPACA2_control_rep3; Homo sapien...,GSM2817751: MIAPACA2_control_rep3; Homo sapien...,9606,Homo sapiens,<NA>,RNA-Seq,...,MIA PACA-2,untreated,<NA>,http://ftp.sra.ebi.ac.uk/vol1/fastq/SRR618/005...,,<NA>,era-fasp@fasp.sra.ebi.ac.uk:vol1/fastq/SRR618/...,,GSE105083,GSM2817751

In [8]:
###get all gse
import pandas as pd
all_srr = pd.read_csv("/home/wt/Drug_splicing/data/test.txt",sep=" ")
all_srr

   experiment_geo_accession         srrs         organ    pair
0                GSM2692577   SRR5800675  Homo_sapiens  PAIRED
1                GSM2692578   SRR5800676  Homo_sapiens  PAIRED
2                GSM2692579   SRR5800677  Homo_sapiens  PAIRED
3                GSM2817751   SRR6181915  Homo_sapiens  SINGLE
4                GSM4286986  SRR10980127  Homo_sapiens  SINGLE
5                GSM4286987  SRR10980128  Homo_sapiens  SINGLE
6                GSM4286988  SRR10980129  Homo_sapiens  SINGLE
7                GSM4286989  SRR10980130  Homo_sapiens  SINGLE
8                GSM4286990  SRR10980131  Homo_sapiens  SINGLE
9                GSM4286991  SRR10980132  Homo_sapiens  SINGLE
10               GSM4305713  SRR11059047  Homo_sapiens  SINGLE
11               GSM7506601  SRR24997945  Homo_sapiens  PAIRED
12               GSM8775911  SRR32238155  Homo_sapiens  PAIRED

In [9]:
from tqdm import tqdm
import sys 
import time

for i in tqdm(range(len(all_srr))):
    try:
        df = db.gsm_to_gse(all_srr.experiment_geo_accession[i])
        df.to_csv("GSM2GSE/"+str(all_srr.experiment_geo_accession[i])+".txt",sep="\t", index=False)
    except:
        time.sleep(20)
        try:
            df = db.gsm_to_gse(all_srr.experiment_geo_accession[i])
            df.to_csv("GSM2GSE/"+str(all_srr.experiment_geo_accession[i])+".txt",sep="\t", index=False)
        except:
            time.sleep(20)

100%|██████████| 13/13 [00:29<00:00,  2.31s/it]